// import { DataTypes } from "sequelize";
// import sequelize from "../client.js";


// const Document = sequelize.define(
//   "Document",
//   {
//     id: {
//       type: DataTypes.BIGINT,
//       autoIncrement: true,
//       primaryKey: true,
//     },

//     content: {
//       type: DataTypes.TEXT,
//       allowNull: false,
//     },

//     embedding: {
//       type: DataTypes.VECTOR(384),
//       allowNull: false,
//     },

//       content_tsv: {
//       type: "TSVECTOR",
//       allowNull: true, // generated by trigger
//     }
//   },
//   {
//     tableName: "documents",
//     timestamps: true,
//     indexes: [
//       {
//         fields: ["embedding"],
//         using: "hnsw",
//         operator: "vector_l2_ops",
//       },
//     ],
//   }
// );

// export default Document;


import { DataTypes } from "sequelize";
import sequelize from "../client.js";

const Document = sequelize.define(
  "Document",
  {
    id: {
      type: DataTypes.BIGINT,
      autoIncrement: true,
      primaryKey: true
    },
    content: {
      type: DataTypes.TEXT,
      allowNull: false
    },
    embedding: {
      type: DataTypes.VECTOR(384),
      allowNull: false
    },
    content_tsv: {
      type: "TSVECTOR",
      allowNull: true // generated by trigger
    }
  },
  {
    tableName: "documents",
    timestamps: true,
    createdAt: "createdAt",
    updatedAt: "updatedAt",
    indexes: [
      {
        name: "documents_embedding",
        using: "hnsw",
        fields: ["embedding"],
        operator: "vector_l2_ops"
      }
    ]
  }
);

export default Document;
